config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#index"
  get "/class_info", to: "pages#class_info"
  # get "/sample_materials", to: "pages#sample_materials", as: :sample_materials

  resources :contacts

  post "contact_us", to: "pages#submit_contact_us", as: :submit_contact_us

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :first_name, :subject, :message, :first_language, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.all.order(created_at: :desc)
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    # Honeypot spam check
    if params[:contact][:nickname].present?
      # Detected as spam
      redirect_to new_contact_path, alert: "Spam detected. Please try again."
      return
    end

    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy!

    respond_to do |format|
      format.html { redirect_to contacts_path, status: :see_other, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :phone, :first_language, :subject, :message, :notes, :nickname)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_contact.html.erb
<!-- Not being used, but kept for reference -->
<div id="<%= dom_id contact %>">
  <p>
    <strong>Date:</strong>
    <%= contact.created_at.strftime("%B %d, %Y") %>
  </p>
  <p>
    <strong>Full name:</strong>
    <%= contact.first_name %> <%= contact.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= contact.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= contact.phone %>
  </p>

  <p>
    <strong>First language:</strong>
    <%= contact.first_language %>
  </p>

  <p>
    <strong>Subject:</strong>
    <%= contact.subject %>
  </p>

  <p>
    <strong>Message:</strong>
    <%= contact.message %>
  </p>

  <p>
    <strong>Notes:</strong>
    <%= contact.notes %>
  </p>

</div>

app/views/contacts/_form.html.erb
<%= bootstrap_form_with(model: contact, url: (defined?(form_url) ? form_url : nil), data: { turbo: false }) do |form| %>
  <div class="card">
    <div class="card-body">
      <%= form.text_field :first_name, required: true, label: raw('First Name <span class="text-danger">*</span>') %>
      <!-- Honeypot field for spam prevention -->
      <div class="hidden-honeypot-field">
        <%= form.text_field :nickname, autocomplete: "off", tabindex: "-1", aria_hidden: "true", placeholder: "Leave this field blank..." %>
      </div>
      <%= form.text_field :last_name %>
      <%= form.email_field :email, required: true, label: raw('Email <span class="text-danger">*</span>') %>
      <%= form.phone_field :phone, placeholder: "Enter your phone number if you'd like a callback" %>
      <%= form.text_field :first_language, required: true, label: raw('First Language <span class="text-danger">*</span>') %>
      <%= form.text_field :subject, required: true, label: raw('Subject <span class="text-danger">*</span>') %>
      <%= form.text_area :message, required: true, label: raw('Message <span class="text-danger">*</span>'), 
      placeholder: 'Enter your message here...', rows: 5 %>
      <% if authenticated? %>
      <%= form.text_area :notes %>
      <% end %>
      <%= form.submit "Send", class: "btn btn-primary w-100 mb-5" %>
    </div>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<% content_for :title, "Editing contact" %>

<h1>Editing contact</h1>

<%= render "form", contact: @contact %>

<br>

<div>
  <%= link_to "Show this contact", @contact %> |
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/index.html.erb
<div class="container">
  <% content_for :title, "Contacts" %>

  <h1>Contacts</h1>
  <p>
    <%= link_to "New Contact", new_contact_path, class: "btn btn-primary" %>
  </p>

  <table class="table table-striped" id="contacts">
    <thead>
      <tr>
        <th>Date</th>
        <th>Full Name</th>
        <th>First Language</th>
        <th>Subject</th>
        <th>Message</th>
        <th>Notes</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @contacts.each do |contact| %>
        <tr id="<%= dom_id contact %>">
          <td><%= contact.created_at.strftime("%B %d, %Y") %></td>
          <td><%= contact.first_name %> <%= contact.last_name %><br />
            <%= contact.email %><br />
            <%= contact.phone %></td>
          <td><%= contact.first_language %></td>
          <td><%= contact.subject %></td>
          <td><%= contact.message %></td>
          <td><%= contact.notes %></td>
          <td><%= link_to "Show", contact, class: "btn btn-info" %></td>
          <td><%= link_to "Edit", edit_contact_path(contact), class: "btn btn-warning" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/contacts/new.html.erb
<% content_for :title, "New contact" %>

<h1>New contact</h1>
<div class="container">
  <%= render "form", contact: @contact %>
</div>
<br>

<div>
  <%= link_to "Back to contacts", contacts_path %>
</div>

app/views/contacts/show.html.erb
<%= render @contact %>

<div>
  <%= link_to "Edit this contact", edit_contact_path(@contact) %> |
  <%= link_to "Back to contacts", contacts_path %>

  <%= button_to "Destroy this contact", @contact, method: :delete %>
</div>